apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - namespace.yml
  - config-maps.yml
  - secrets.yml
  - rbac.yml
  - deployments.yml
  - services.yml
  - network-policies.yml
  - ingress.yml

patches:
  # Changes ArgoCD service to LoadBalancer so the UI can be accessed without an ingress controller or port-forwarding
  - target:
      kind: Service
      name: argocd-server
    path: service-patch.yml
  # Runs ArgoCD in insecure mode, allowing an ingress controller to handle TLS termination
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --insecure
    target:
      kind: Deployment
      name: argocd-server