apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd.yml
  - cert-manager.yml
  - cloudnative-pg.yml
  - external-snapshotter.yml
  - metallb.yml
  - prometheus-operator.yml
  - sealed-secrets.yml
  - traefik.yml